[package]
name = "warrant-host"
default-run = "warrant-host"
version = "0.1.0"
edition = "2021"

[dependencies]
warrant-policy = { path = "../core" }
warrant-methods = { path = "../methods" }
risc0-zkvm = { workspace = true, features = ["client", "disable-dev-mode"] }
serde_json = "1.0"
bincode.workspace = true
hex = "0.4"
anyhow = "1.0"

k256.workspace = true
