[package]
name = "warrant-verified-policy"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[dependencies]
vstd = "=0.0.0-2026-09-20-0158"
serde = { workspace = true, optional = true }

[features]
default = ["serde"]
serde = ["dep:serde"]

[package.metadata.verus]
verify = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(verus_keep_ghost)', 'cfg(verus_only)'] }
