"""Writes the whole beancount file from the event store (spec section 8.2).
The file is regenerated, never edited, so a second export gives the same bytes."""
import datetime as dt
import os
import re
import tempfile

from .. import match as m

ACCOUNT_PART = re.compile(r"^[A-Z][A-Za-z0-9-]*$")
SCALE = 10**6


def usdc(units):
    sign = "-" if units < 0 else ""
    units = abs(units)
    return f"{sign}{units // SCALE}.{units % SCALE:06d}"


def day(ts):
    return dt.datetime.fromtimestamp(ts, dt.timezone.utc).date()


def vendor_account(cfg, vendors, recipient):
    suffix = vendors.get(recipient.lower()) or "V" + recipient[2:10].lower()
    if not ACCOUNT_PART.match(suffix):
        raise ValueError(f"Vendor account name {suffix!r} is not a valid beancount account part")
    return f"{cfg.expense_prefix}:{suffix}"


def q(s):
    s = str(s).replace("\\", "\\\\").replace('"', '\\"')
    return '"' + s.replace("\n", "\\n").replace("\r", "\\r") + '"'


def render(store, chain, cfg, vendors):
    events = store.events(chain.chain_id, customer=chain.customer)
    invoices = store.invoices()
    entries = []  # (date, sequence, text)
    accounts = {cfg.escrow_account, cfg.wallet_account}
    escrow_balance, end_of_day, closing_days = 0, {}, set()
    for seq, inv in enumerate(invoices):
        # Every currency the checker supports has 2 minor units (ISO 4217).
        payable = "unknown" if inv["payable_minor"] is None else \
            f'{inv["payable_minor"] // 100}.{inv["payable_minor"] % 100:02d} {inv["currency"]}'
        entries.append((day(inv["recorded_at"]), 0, seq,
            f'{day(inv["recorded_at"])} custom "warrant-invoice" {q(inv["document_hash"])}\n'
            f'  obligation: {q(inv["obligation_id"])}\n  invoice: {q(inv["invoice_number"])}\n'
            f'  po: {q(inv["po_id"])}\n  payable: {q(payable)}\n'))
    for seq, e in enumerate(events):
        d, date = e["data"], day(e["block_time"])
        txid = f'{e["tx_hash"]}:{e["log_index"]}'
        link = f'^order-{d["orderId"]}'
        if e["event"] == "Offered":
            amount = d["terms"]["maxTotal"]
            escrow_balance += amount
            entries.append((date, 1, seq,
                f'{date} * "Warrant" {q("Offered order " + d["orderId"][:10])} {link}\n'
                f'  txid: {q(txid)}\n  po: {q(d["terms"]["poId"])}\n  recipient: {q(d["terms"]["recipient"])}\n'
                f'  {cfg.escrow_account}  {usdc(amount)} USDC\n  {cfg.wallet_account}  {usdc(-amount)} USDC\n'))
        elif e["event"] == "Paid":
            status, order, inv = m.match(store, e)
            recipient = order["recipient"] if order else "0x00000000unknown"
            account = vendor_account(cfg, vendors, recipient)
            accounts.add(account)
            escrow_balance -= d["amount"]
            label = inv["invoice_number"] if inv else "obligation " + d["obligationId"][:10]
            payee = account.rsplit(":", 1)[1]
            entries.append((date, 1, seq,
                f'{date} * {q(payee)} {q("Paid " + label)} {link} ^{d["documentHash"]}\n'
                f'  txid: {q(txid)}\n  obligation: {q(d["obligationId"])}\n  document: {q(d["documentHash"])}\n'
                f'  evidence: {q(d["evidenceHash"])}\n  authenticator: {q(d["authenticator"])}\n'
                f'  match: {q(status)}\n'
                f'  {account}  {usdc(d["amount"])} USDC\n  {cfg.escrow_account}  {usdc(-d["amount"])} USDC\n'))
        elif e["event"] == "Closed":
            amount = d["refunded"]
            escrow_balance -= amount
            entries.append((date, 1, seq,
                f'{date} * "Warrant" {q("Closed order " + d["orderId"][:10])} {link}\n  txid: {q(txid)}\n'
                f'  {cfg.wallet_account}  {usdc(amount)} USDC\n  {cfg.escrow_account}  {usdc(-amount)} USDC\n'))
        end_of_day[date] = escrow_balance
        if e["event"] == "Closed":
            closing_days.add(date)
    # A balance assertion holds at the start of its date, so the assertion for the
    # day of a Closed event is dated the next day and carries that day's end balance.
    for date in sorted(closing_days):
        nxt = date + dt.timedelta(days=1)
        entries.append((nxt, 2, 0,
            f'{nxt} balance {cfg.escrow_account}  {usdc(end_of_day[date])} ~ 0.000001 USDC\n'))
    first = min([e[0] for e in entries], default=dt.date(2026, 1, 1))
    head = [f"; Generated by warrant-ledger. Do not edit. Source: chain {chain.chain_id}, escrow {chain.escrow}\n",
            'option "operating_currency" "USDC"\n',
            f'plugin "warrant_ledger.beancount_plugin" "unpaid_after_days={cfg.unpaid_after_days}"\n\n',
            f"{first} commodity USDC\n"]
    head += [f"{first} open {a} USDC\n" for a in sorted(accounts)]
    body = [text for *_, text in sorted(entries, key=lambda x: x[:3])]
    return "".join(head) + "\n" + "\n".join(body)


def export(store, chain, cfg, vendors):
    text = render(store, chain, cfg, vendors)
    folder = os.path.dirname(os.path.abspath(cfg.path))
    fd, tmp = tempfile.mkstemp(dir=folder, prefix=".warrant-ledger-", suffix=".tmp")
    with os.fdopen(fd, "w") as f:
        f.write(text)
    os.replace(tmp, cfg.path)
    return cfg.path
