use risc0_zkvm::{InnerReceipt, Receipt};
use std::{fs, path::PathBuf};
use warrant_methods::WARRANT_GUEST_ID;
use warrant_policy::{authorize, Input};

fn artifact_dir() -> PathBuf {
    std::env::var_os("WARRANT_RECEIPT_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../artifacts"))
}

fn receipt(name: &str) -> Receipt {
    let dir = artifact_dir();
    bincode::deserialize(
        &fs::read(dir.join(format!("{name}.receipt"))).expect("Generate real demo receipts first"),
    )
    .unwrap()
}

fn input(name: &str) -> Input {
    let dir = artifact_dir();
    serde_json::from_slice(&fs::read(dir.join(format!("{name}.json"))).unwrap()).unwrap()
}

#[test]
#[ignore = "requires the two real receipts generated by the documented demo commands"]
fn different_policies_and_recipients_verify_against_one_interpreter() {
    let a = receipt("request");
    let b = receipt("alternative");
    for (name, receipt) in [("request", &a), ("alternative", &b)] {
        assert!(
            matches!(receipt.inner, InnerReceipt::Succinct(_)),
            "expected a real succinct receipt"
        );
        receipt.verify(WARRANT_GUEST_ID).unwrap();
        assert_eq!(
            receipt.journal.bytes,
            authorize(&input(name)).unwrap().journal()
        );
    }
    assert_ne!(&a.journal.bytes[0..32], &b.journal.bytes[0..32]); // policy hash
    assert_ne!(&a.journal.bytes[128..160], &b.journal.bytes[128..160]); // recipient
}

#[test]
#[ignore = "requires a real receipt generated by the documented demo commands"]
fn changing_any_public_authorization_word_invalidates_receipt() {
    let original = receipt("request");
    for word in 0..12 {
        let mut forged = original.clone();
        forged.journal.bytes[word * 32 + 31] ^= 1;
        assert!(forged.verify(WARRANT_GUEST_ID).is_err(), "word {word}");
    }
}

#[test]
#[ignore = "requires a real receipt generated by the documented demo commands"]
fn another_interpreter_id_is_not_accepted() {
    let mut wrong_image = WARRANT_GUEST_ID;
    wrong_image[0] ^= 1;
    assert!(receipt("request").verify(wrong_image).is_err());
}
