//! Test vectors shared with the Python ledger connector. The committed files must
//! equal what this test generates; set WARRANT_WRITE_VECTORS=1 to rewrite them.

#[path = "../../core/examples/common/invoice.rs"]
mod invoice_fixture;

use invoice_fixture::*;
use serde_json::json;
use std::{fs, path::Path};
use warrant_ids::*;
use warrant_policy::evidence::*;

const CHAIN_ID: u64 = 5042002;
const ESCROW: [u8; 20] = [0x11; 20];
const CUSTOMER: [u8; 20] = [0x22; 20];
const POLICY_HASH: [u8; 32] = [0x33; 32];

fn check(path: &str, generated: &[u8]) {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join(path);
    if std::env::var_os("WARRANT_WRITE_VECTORS").is_some() {
        fs::write(&path, generated).unwrap();
    }
    let committed = fs::read(&path).expect("vector file missing; run with WARRANT_WRITE_VECTORS=1");
    assert_eq!(committed, generated, "{} is stale", path.display());
}

#[test]
fn facts_match_the_checker() {
    let xml = doc().xml();
    let f = facts(&xml).unwrap();
    let parsed = parse_invoice(&xml).unwrap();
    assert_eq!(f["documentHash"], hex32(&parsed.doc_hash));
    assert_eq!(f["obligationId"], hex32(&obligation_id(TAX_ID, "INV-1001")));
    assert_eq!(f["poId"], hex32(&reference_hash("PO-77")));
    assert_eq!(f["taxIdHash"], hex32(&tax_id_hash(TAX_ID)));
    assert_eq!(f["payable"], 1320 * USDC);
    assert_eq!(f["usd"], true);
    assert_eq!(f["totalsConsistent"], true);
}

#[test]
fn denied_document_is_an_error() {
    assert!(facts(b"<NotAnInvoice/>").is_err());
}

#[test]
fn order_id_matches_the_contract_layout() {
    // abi.encode of five static words, hashed with keccak256.
    let mut encoded = Vec::new();
    let mut word = [0u8; 32];
    word[24..].copy_from_slice(&CHAIN_ID.to_be_bytes());
    encoded.extend_from_slice(&word);
    for a in [ESCROW, CUSTOMER] {
        let mut w = [0u8; 32];
        w[12..].copy_from_slice(&a);
        encoded.extend_from_slice(&w);
    }
    encoded.extend_from_slice(&POLICY_HASH);
    encoded.extend_from_slice(&reference_hash("PO-77"));
    use sha3::{Digest, Keccak256};
    let expected: [u8; 32] = Keccak256::digest(&encoded).into();
    assert_eq!(
        order_id(
            CHAIN_ID,
            &ESCROW,
            &CUSTOMER,
            &POLICY_HASH,
            &reference_hash("PO-77")
        ),
        expected
    );
}

#[test]
fn committed_vectors_are_current() {
    let xml = doc().xml();
    let vectors = json!({
        "note": "Generated by ids/tests/vectors.rs from the synthetic invoice fixture.",
        "document": "invoice.xml",
        "facts": facts(&xml).unwrap(),
        "obligation": {"sellerTaxId": TAX_ID, "invoiceNumber": "INV-1001",
                       "hash": hex32(&obligation_id(TAX_ID, "INV-1001"))},
        "obligationNormalised": {"sellerTaxId": " us 12 3456789 ", "invoiceNumber": " INV-1001 ",
                       "hash": hex32(&obligation_id(" us 12 3456789 ", " INV-1001 "))},
        "reference": {"text": "PO-77", "hash": hex32(&reference_hash("PO-77"))},
        "taxId": {"text": TAX_ID, "hash": hex32(&tax_id_hash(TAX_ID))},
        "orderId": {"chainId": CHAIN_ID, "escrow": format!("0x{}", hex::encode(ESCROW)),
                    "customer": format!("0x{}", hex::encode(CUSTOMER)),
                    "policyHash": hex32(&POLICY_HASH), "poId": hex32(&reference_hash("PO-77")),
                    "hash": hex32(&order_id(CHAIN_ID, &ESCROW, &CUSTOMER, &POLICY_HASH, &reference_hash("PO-77")))},
    });
    check("tests/data/invoice.xml", &xml);
    check(
        "tests/data/vectors.json",
        format!("{}\n", serde_json::to_string_pretty(&vectors).unwrap()).as_bytes(),
    );
}
